/**
 * Generate `packages/cli/man/snack.1` from the CLI's own help and the specification's prose.
 *
 * The page is checked in and `npm run check` regenerates it in memory and compares bytes, so a
 * flag added to `main.js` and never regenerated fails the gate. Nothing here holds prose of its
 * own: the descriptions come from Commander and the paragraphs from
 * `docs/specification/cli.md`, which is the document this project already treats as the contract.
 *
 * Run it as `node scripts/generate-man.mjs` to write the file.
 */

import { readFile, mkdir, writeFile } from "node:fs/promises";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { commandSurface, extractProse } from "./man-surface.mjs";

export const MAN_PAGE = new URL("../packages/cli/man/snack.1", import.meta.url);
const SPECIFICATION = new URL("../docs/specification/cli.md", import.meta.url);
const PACKAGE = new URL("../packages/cli/package.json", import.meta.url);

/**
 * @typedef {object} PageInput
 * @property {string} version
 * @property {import("./man-surface.mjs").Command[]} surface
 * @property {Record<string, import("./man-surface.mjs").Prose>} prose
 */

/**
 * Render the whole page.
 *
 * The `.TH` line carries no date. A date would be the one field that changes without the CLI
 * changing, and the gate downstream compares bytes -- a page that cannot reproduce is a gate that
 * fails on the calendar rather than on a defect.
 *
 * @param {PageInput} input
 * @returns {string}
 */
export function renderManPage(input) {
  const root = input.surface.find((command) => command.name === "snack");
  /** @type {string[]} */
  const lines = [
    `.\\" Generated by scripts/generate-man.mjs. Do not edit; run \`node scripts/generate-man.mjs\`.`,
    `.TH SNACK 1 "" "snack ${input.version}" "User Commands"`,
    ".SH NAME",
    `snack \\- ${roff(root?.description ?? "")}`,
    ".SH SYNOPSIS",
    ".B snack",
    `.RI [ command ] " " [ options ]`,
    ".SH DESCRIPTION",
    ...paragraphs(input.prose["Global Behavior"]?.paragraphs ?? []),
    ".SH COMMANDS",
  ];

  // The specification documents `snack setup` once and `snack config` once, while the CLI publishes
  // `setup opencode`, `config get` and the rest. The prose is written per section, so it is printed
  // per section: repeating §12.2 under both `setup opencode` and `setup claude` would put the same
  // six paragraphs on the page twice.
  /** @type {string | null} */
  let lastKey = null;
  for (const command of input.surface) {
    if (command.name === "snack") continue;
    const key = proseKey(input.prose, command.name);
    if (key !== null && key !== lastKey) {
      lines.push(`.SS ${roff(key)}`);
      lines.push(...paragraphs(input.prose[key].paragraphs));
    }
    lastKey = key;

    lines.push(`.TP`);
    lines.push(`.B ${roff(command.usage)}`);
    lines.push(roff(command.description));
    for (const flag of command.flags) {
      lines.push(".RS");
      lines.push(".TP");
      lines.push(
        `.BR ${roff(flag.flag)}${flag.argument === null ? "" : ` " " ${roff(flag.argument)}`}`,
      );
      lines.push(roff(flag.description));
      lines.push(".RE");
    }
  }

  lines.push(".SH EXIT STATUS");
  lines.push(...paragraphs(input.prose["Exit Codes"]?.paragraphs ?? []));

  lines.push(".SH GLOBAL OPTIONS");
  for (const flag of root?.flags ?? []) {
    lines.push(".TP");
    lines.push(
      `.BR ${roff(flag.flag)}${flag.argument === null ? "" : ` " " ${roff(flag.argument)}`}`,
    );
    lines.push(roff(flag.description));
  }

  lines.push(".SH SEE ALSO");
  lines.push("The full specification and the documentation live in the repository:");
  lines.push(".UR https://github.com/Duck1201/snack");
  lines.push(".UE");

  return `${lines.join("\n")}\n`;
}

/**
 * The prose written for this command, or for the group it belongs to.
 *
 * `docs/specification/cli.md` documents `snack setup` once and `snack config` once, while the CLI
 * publishes `setup opencode`, `config get` and the rest. The longest heading that prefixes the
 * command is the one written about it.
 *
 * @param {Record<string, import("./man-surface.mjs").Prose>} prose
 * @param {string} name @returns {string | null}
 */
function proseKey(prose, name) {
  const full = `snack ${name}`;
  return (
    Object.keys(prose)
      .filter((heading) => full === heading || full.startsWith(`${heading} `))
      .sort((left, right) => right.length - left.length)[0] ?? null
  );
}

/**
 * Prose as roff blocks. A bullet keeps its shape; everything else is a paragraph.
 *
 * @param {string[]} values
 */
function paragraphs(values) {
  return values.flatMap((value) => {
    const bullet = /^-\s+(.*)$/u.exec(value);
    return bullet ? [".IP \\(bu 2", roff(String(bullet[1]))] : [".PP", roff(value)];
  });
}

/**
 * Make one line safe to hand to roff.
 *
 * A backslash introduces an escape and a leading `.` or `'` at column zero is read as a macro
 * rather than as text, which drops the line silently. Markdown's inline markers are stripped
 * because the specification is written for a Markdown reader and roff is not one.
 *
 * @param {string} value
 */
function roff(value) {
  const text = value
    .replaceAll("\\", "\\e")
    .replaceAll(/`([^`]+)`/gu, "$1")
    .replaceAll(/\*\*([^*]+)\*\*/gu, "$1")
    .replaceAll(/\[([^\]]+)\]\([^)]+\)/gu, "$1")
    .replaceAll("—", "-")
    .replaceAll("→", "->");
  return /^[.']/u.test(text) ? `\\&${text}` : text;
}

/** Read the inputs, render, and write the page. */
export async function generate() {
  const { run } = await import("../packages/cli/src/main.js");
  const version = JSON.parse(await readFile(PACKAGE, "utf8")).version;

  /** @type {{value: string}} */
  const out = { value: "" };
  const sink = {
    /** @param {string} chunk */
    write(chunk) {
      out.value += chunk;
      return true;
    },
  };

  const surface = await commandSurface(async (argv) => {
    out.value = "";
    await run(["node", "snack", ...argv, "--help"], { stdout: sink, stderr: sink });
    return out.value;
  });

  return renderManPage({
    version,
    surface,
    prose: extractProse(await readFile(SPECIFICATION, "utf8")),
  });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const page = await generate();
  await mkdir(new URL(".", MAN_PAGE), { recursive: true });
  await writeFile(MAN_PAGE, page, "utf8");
  process.stdout.write(`wrote ${fileURLToPath(MAN_PAGE)}\n`);
}
