import assert from "node:assert/strict";
import { test } from "node:test";

import { commandSurface, extractProse, flagMap, parseHelp } from "./man-surface.mjs";
import { renderManPage } from "./generate-man.mjs";

// The man page and `contracts.test.js` both describe the same published surface, so they read it
// from one place. That place is the help text rather than Commander's object graph: the help is
// what a user is actually promised, and a surface read from the object graph would still pass with
// a flag the help had stopped mentioning.

test("a flag whose description wrapped onto the next line keeps the whole description", () => {
  // Commander wraps at the terminal width, so a long description arrives as a flag line plus an
  // indented continuation. Reading only the first line silently truncates the man page, and the
  // byte-comparison gate would then hold the truncation in place as the expected output.
  const help = [
    "Usage: snack update [options]",
    "",
    "bring the CLI and the capture plugin to versions that belong",
    "together",
    "",
    "Options:",
    "  --yes             skip the confirmation and apply the plan that was",
    "                    shown",
    "  --dry-run         report the plan without applying it",
    "  -h, --help        display help for command",
    "",
  ].join("\n");

  assert.deepEqual(parseHelp(help).flags, [
    {
      flag: "--yes",
      argument: null,
      description: "skip the confirmation and apply the plan that was shown",
    },
    { flag: "--dry-run", argument: null, description: "report the plan without applying it" },
    { flag: "--help", argument: null, description: "display help for command" },
  ]);
});

test("a command group is walked into, and contributes its children rather than itself", async () => {
  // `snack config` takes no action of its own; `snack config get` does. A surface that stopped at
  // the group would document a command nobody can run and omit the three that they can.
  /** @param {string[]} argv */
  const help = async (argv) => {
    if (argv.length === 0) {
      return [
        "Usage: snack [options] [command]",
        "",
        "Commands:",
        "  config",
        "  help [command]",
      ].join("\n");
    }
    if (argv[0] === "config" && argv.length === 1) {
      return [
        "Usage: snack config [options] [command]",
        "",
        "inspect or update local configuration",
        "",
        "Commands:",
        "  path [options]",
        "  help [command]",
      ].join("\n");
    }
    return [
      "Usage: snack config path [options]",
      "",
      "show the SNACK configuration path",
      "",
      "Options:",
      "  --json    emit one versioned JSON document",
    ].join("\n");
  };

  const surface = await commandSurface(help);

  assert.deepEqual(
    surface.map((entry) => entry.name),
    ["snack", "config path"],
  );
  assert.equal(surface[1].description, "show the SNACK configuration path");
});

test("the walk over the real CLI reaches every command with a description and flags", async () => {
  // A control, not a second copy of the frozen literal -- `contracts.test.js` asserts that map and
  // now reads it from this module, so duplicating it here would only be a third place to drift.
  // What this pins is that the parser matched something: a regex that quietly stopped matching
  // would produce an empty surface, and every downstream gate comparing generated bytes to
  // generated bytes would go on passing forever.
  const { makeRunFixture } = await import("../packages/cli/test/fixtures/run-fixture.js");
  const { run } = await import("../packages/cli/src/main.js");
  const fixture = await makeRunFixture("snack-man-surface-");

  const surface = await commandSurface(async (argv) => {
    fixture.stdout.value = "";
    fixture.stderr.value = "";
    await run(["node", "snack", ...argv, "--help"], fixture.options);
    return `${fixture.stdout.value}${fixture.stderr.value}`;
  });

  assert.ok(surface.length > 10, `expected the whole CLI, walked ${surface.length}`);
  for (const command of surface) {
    assert.ok(command.usage.startsWith("snack"), `${command.name} has no usage line`);
    assert.ok(command.flags.length > 0, `${command.name} reports no flags, not even --help`);
    assert.ok(
      command.flags.every((flag) => flag.description !== ""),
      `${command.name} has a flag whose description was dropped`,
    );
  }
  // The group is walked into rather than listed: `config` is not a command, `config get` is.
  const names = surface.map((command) => command.name);
  assert.ok(names.includes("config get"));
  assert.ok(!names.includes("config"));
  assert.deepEqual(flagMap(surface).status, [
    "--source",
    "--no-sync",
    "--prompt-file",
    "--json",
    "--help",
  ]);
});

test("a command's prose comes from its own section of the specification", () => {
  // The man page holds no prose of its own. If it did, it would be a second description of the
  // same commands, maintained by whoever last remembered it existed.
  const specification = [
    "## 12. CLI Contract",
    "",
    "### 12.2 `snack setup`",
    "",
    "```text",
    "snack setup <opencode|claude> [--dry-run]",
    "```",
    "",
    "Setup is idempotent.",
    "",
    "It asks only for what it cannot observe.",
    "",
    "### 12.3 `snack status`",
    "",
    "```text",
    "snack status [--source <alias>] [--json]",
    "```",
    "",
    "Human output has two shapes.",
    "",
    "### 12.11 Exit Codes",
    "",
    "`0` success.",
  ].join("\n");

  const prose = extractProse(specification);

  assert.deepEqual(prose["snack setup"].paragraphs, [
    "Setup is idempotent.",
    "It asks only for what it cannot observe.",
  ]);
  assert.deepEqual(prose["snack setup"].synopsis, ["snack setup <opencode|claude> [--dry-run]"]);
  assert.deepEqual(prose["snack status"].synopsis, ["snack status [--source <alias>] [--json]"]);
  // A section that names no command is not prose for one. `12.11 Exit Codes` documents the whole
  // CLI, and attaching it to whichever command happened to precede it would be worse than dropping
  // it: the man page would state one command's exit codes as if they were only that command's.
  assert.equal(Object.hasOwn(prose, "snack Exit Codes"), false);
});

test("every flag and command in the surface reaches the roff output", () => {
  // The control for the byte-comparison gate below. That gate compares the generator's output to
  // the generator's output, so it passes forever if a regex quietly stops matching and the page
  // goes empty. This one asserts the page actually says what the surface holds.
  const page = renderManPage({
    version: "9.9.9",
    surface: [
      {
        name: "snack",
        usage: "snack [options] [command]",
        description: "Know before you feed the model.",
        flags: [
          { flag: "--json", argument: null, description: "emit one versioned JSON document" },
        ],
      },
      {
        name: "status",
        usage: "snack status [options]",
        description: "assess next-prompt viability",
        flags: [
          { flag: "--source", argument: "<alias>", description: "capacity-source alias" },
          {
            flag: "--no-sync",
            argument: null,
            description: "use already synchronized observations",
          },
        ],
      },
    ],
    prose: {
      "snack status": { synopsis: [], paragraphs: ["Human output has two shapes."] },
    },
  });

  assert.match(page, /^\.TH SNACK 1 .*9\.9\.9/mu);
  assert.match(page, /^\.SS snack status$/mu);
  assert.match(page, /capacity-source alias/u);
  assert.match(page, /use already synchronized observations/u);
  assert.match(page, /Human output has two shapes\./u);
  // The argument placeholder belongs to the flag: `--source` alone tells a reader nothing about
  // whether it takes a value.
  assert.match(page, /--source.*<alias>/u);
});

test("roff control characters in a description cannot start a macro line", () => {
  // A description beginning with `.` or `'` at column zero is read by roff as a macro rather than
  // as text, which silently drops the line. Nothing in the CLI does this today, which is exactly
  // why it needs a test: the day a description starts with one, the man page loses it quietly.
  const page = renderManPage({
    version: "1.0.0",
    surface: [
      {
        name: "snack",
        usage: "snack",
        description: ".this begins with a dot",
        flags: [{ flag: "--json", argument: null, description: "'and this with a quote" }],
      },
    ],
    prose: {},
  });

  for (const line of page.split("\n")) {
    if (line.startsWith(".") || line.startsWith("'")) {
      assert.match(
        line,
        /^\.(TH|SH|SS|TP|PP|BR?|IR?|RI|UR|UE|nf|fi|\\"|\\&)/u,
        `unescaped roff line: ${line}`,
      );
    }
  }
});

test("a markdown bullet list stays a list rather than collapsing into one sentence", () => {
  // The specification writes responsibilities and guarantees as bullets. Joined into a paragraph
  // they read as "- discover local source locations; - create/edit validated mappings; - ..." in
  // one run-on line, which is worse than not carrying them.
  const prose = extractProse(
    [
      "### 12.2 `snack setup`",
      "",
      "Responsibilities:",
      "",
      "- discover sources;",
      "- select profiles;",
      "",
      "Setup is idempotent.",
    ].join("\n"),
  );

  assert.deepEqual(prose["snack setup"].paragraphs, [
    "Responsibilities:",
    "- discover sources;",
    "- select profiles;",
    "Setup is idempotent.",
  ]);

  const page = renderManPage({
    version: "1.0.0",
    surface: [
      { name: "snack", usage: "snack", description: "root", flags: [] },
      {
        name: "setup opencode",
        usage: "snack setup opencode",
        description: "configure",
        flags: [],
      },
    ],
    prose,
  });

  assert.match(page, /^\.IP \\\(bu 2\ndiscover sources;$/mu);
});

test("the checked-in snack.1 is what the generator produces from today's surface", async () => {
  // The page is committed so it can be packed and read without a build step, which means it can go
  // stale the moment a flag moves. Regenerating in memory and comparing bytes is what makes "run
  // the generator" a gate rather than a habit.
  const { readFile } = await import("node:fs/promises");
  const { generate, MAN_PAGE } = await import("./generate-man.mjs");

  assert.equal(
    await readFile(MAN_PAGE, "utf8"),
    await generate(),
    "packages/cli/man/snack.1 is stale -- run `node scripts/generate-man.mjs`",
  );
});

test("every flag the CLI publishes is documented in the specification's synopsis", async () => {
  // This is the gate that makes "undocumented" mean undocumented rather than merely
  // un-regenerated. The generator would happily render a flag that no prose has ever mentioned;
  // what must not be possible is shipping one.
  const { readFile } = await import("node:fs/promises");
  const { makeRunFixture } = await import("../packages/cli/test/fixtures/run-fixture.js");
  const { run } = await import("../packages/cli/src/main.js");

  const fixture = await makeRunFixture("snack-man-documented-");
  const surface = await commandSurface(async (argv) => {
    fixture.stdout.value = "";
    fixture.stderr.value = "";
    await run(["node", "snack", ...argv, "--help"], fixture.options);
    return `${fixture.stdout.value}${fixture.stderr.value}`;
  });
  const prose = extractProse(
    await readFile(new URL("../docs/specification/cli.md", import.meta.url), "utf8"),
  );

  // `--help` and `--version` are documented once, in §12.1, as belonging to every command. Naming
  // them in each synopsis would say nothing and would have to be repeated forever.
  const universal = new Set(["--help", "--version"]);
  /** @type {string[]} */
  const undocumented = [];

  for (const command of surface) {
    if (command.name === "snack") continue;
    const key = Object.keys(prose)
      .filter((heading) => `snack ${command.name}`.startsWith(heading))
      .sort((left, right) => right.length - left.length)[0];
    const synopsis = key === undefined ? "" : prose[key].synopsis.join(" ");
    for (const { flag } of command.flags) {
      if (universal.has(flag)) continue;
      if (!synopsis.includes(flag)) undocumented.push(`${command.name} ${flag}`);
    }
  }

  assert.deepEqual(
    undocumented,
    [],
    "these flags exist and no synopsis in docs/specification/cli.md declares them",
  );
});
